In [1]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4])

result=arr**2                #vectorization

In [5]:
result

array([ 1,  4,  9, 16])

In [6]:
result+10                    #broadcast

array([11, 14, 19, 26])

In [7]:
arr1=np.array([[1,2,3],
               [4,5,6]
              ])

arr2=np.array([1,2,3])


res=arr1+arr2     #broadcast arr2 across arr1


In [8]:
res

array([[2, 4, 6],
       [5, 7, 9]])