In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr=np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
np.linspace(1,100,5)


array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [11]:
myarr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])


In [12]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
myarr.shape

(4, 3)

In [14]:
myarr.size

12

In [15]:
myarr.ndim

2

In [16]:
myarr.dtype

dtype('int64')

In [17]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float64')

In [18]:
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
myarr.dtype


dtype('float64')

In [20]:
myarr.astype('int64')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
myarr.dtype

dtype('float64')

In [62]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [63]:
reshaped=myarr.reshape((3,4))

In [64]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
flattened=myarr.flatten()

In [69]:
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])