In [1]:
import numpy as np

In [6]:
# ex-1


arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3, 3)

In [9]:
#ex-2

arr2=np.array([1.1,2.2,3.3])

In [10]:
arr3=arr2.astype('int64')

In [11]:
arr3

array([1, 2, 3])

In [12]:
#ex-3

arr4= np.array([1,2,3,4,5,6])

In [13]:
arr4[[1,3,5]]

array([2, 4, 6])

In [14]:
#ex- 4

arr5= np.array([1,2,3,4,5,6,7,8,9])

In [15]:
arr5.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#ex- 5

arr6=np.array([1,2,50,55,77,88,99])

In [17]:
arr6[arr6>50]

array([55, 77, 88, 99])