In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
flat=arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[1]

np.int64(2)

In [8]:
flat[2:5]

array([3, 4, 5])

In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [24]:
#slicing return view not copy

flat

array([    1,     2, 33333,     4,     5,     6,     7,     8,     9,
          10,    11,    12])

In [25]:
b=flat[2:7]

In [26]:
b

array([33333,     4,     5,     6,     7])

In [27]:
b[0]=33333

In [28]:
b

array([33333,     4,     5,     6,     7])

In [29]:
flat

array([    1,     2, 33333,     4,     5,     6,     7,     8,     9,
          10,    11,    12])

In [33]:
#fancy indexing

arr=np.array([1,2,3,4,5,6,7,8,9])


In [34]:
arr[[1,3,5]]


array([2, 4, 6])

In [35]:
#boolean masking

arr[arr>7]

array([8, 9])