In [14]:
import numpy as np

In [15]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(np.sum(arr,axis=0)) #sum such that all row element participate 

[12 15 18]


In [18]:
print(np.sum(arr,axis=1))  #sum such that all col element participate

[ 6 15 24]


In [19]:
#indexing in 2d

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print(arr[0,1])

2


In [21]:
print(arr[0:2 ,1:3])

[[2 3]
 [5 6]]


In [22]:
#indexing in 3d array 


In [27]:
arr3=np.array([ 
    
    [[1,2,3],
     [4,5,6]], #2d array -0
               
               
    [[7,8,9],
     [10,11,12]]  #2d array -1

         ] )
              
              
              
             
             
             
    
    

    
     
     

In [33]:
print(arr3[0,1,2])   #[ which 2d array(depth) , row , col ]

6


In [34]:
print(arr3[ :,0,: ])  

[[1 2 3]
 [7 8 9]]


In [35]:
arr3[ : , 0 , : ]=0


In [36]:
arr3

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])