In [10]:
#using python list
import numpy as  np
import time

size=1_000_000

l1=list(range(size))
l2=list(range(size))

start = time.time()
add= [x+y for x,y in zip(l1,l2)]
end=time.time()
print(add[0:10])

print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.04737257957458496


In [11]:
#using numpy array
import numpy as np
import time

size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))


start = time.time()
add=l1+l2
end=time.time()

print(add[0:10])

print(end-start)

[ 0  2  4  6  8 10 12 14 16 18]
0.006204128265380859


In [23]:
#explain zip

l1=[1,2,3]
l2=[4,5,6]

list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [13]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [18]:
arr=np.array([[1,2,3], [4,5,6]])

In [19]:
type(arr)

numpy.ndarray

In [21]:
arr.shape

(2, 3)

In [24]:
l3=[1,2,3,4,5]

In [29]:
#time taken when using list in python

start = time.time()
list_sq= [x**2 for x in l3]
end = time.time()

print(list_sq)
print(end-start)


[1, 4, 9, 16, 25]
0.00014090538024902344


In [35]:
#time taken when using numpy

arr=np.array(l3)

start = time.time()
numpy_sq= arr**2
end=time.time()

print(numpy_sq)
print(end-start)

[ 1  4  9 16 25]
0.0001289844512939453
